server.port=${PORT:8081}
logging.level.org.atmosphere=warn

# Launch the default browser when starting the application in development mode
vaadin.launch-browser=true

# To improve the performance during development.
# For more information https://vaadin.com/docs/latest/flow/integrations/spring/configuration#special-configuration-parameters
vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode,com.example

# Let Hibernate update the schema automatically or create it if it does not exist.
#
# DO NOT DO THIS IN PRODUCTION!
#
# Instead, use Flyway or another controlled way of managing your database schema.
# See https://vaadin.com/docs/latest/building-apps/forms-data/add-flyway for instructions.

##############################
#        DATABASE
##############################
spring.datasource.url=jdbc:postgresql://localhost:5432/library_db
spring.datasource.username=library_user
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
